"""initial v0.1 schema

Revision ID: 55a60c1e5af7
Revises:
Create Date: 2026-08-12 14:04:26.999506
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "55a60c1e5af7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("tax_id", sa.String(length=32), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_active"), "companies", ["active"], unique=False)
    op.create_index(op.f("ix_companies_tax_id"), "companies", ["tax_id"], unique=True)
    op.create_table(
        "plants",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "code", name="uq_plants_company_code"),
    )
    op.create_index(op.f("ix_plants_active"), "plants", ["active"], unique=False)
    op.create_index(op.f("ix_plants_company_id"), "plants", ["company_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "SUPER_ADMIN",
                "ADMIN",
                "MAINTENANCE_MANAGER",
                "TECHNICIAN",
                "VIEWER",
                name="user_role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "email", name="uq_users_company_email"),
    )
    op.create_index(op.f("ix_users_active"), "users", ["active"], unique=False)
    op.create_index(op.f("ix_users_company_id"), "users", ["company_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "assets",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("manufacturer", sa.String(length=120), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("serial_number", sa.String(length=120), nullable=True),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "STOPPED",
                "MAINTENANCE",
                "OUT_OF_SERVICE",
                name="asset_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "criticality",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="asset_criticality",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "code", name="uq_assets_company_code"),
    )
    op.create_index(
        "ix_assets_company_criticality", "assets", ["company_id", "criticality"], unique=False
    )
    op.create_index(op.f("ix_assets_company_id"), "assets", ["company_id"], unique=False)
    op.create_index("ix_assets_company_status", "assets", ["company_id", "status"], unique=False)
    op.create_index(op.f("ix_assets_name"), "assets", ["name"], unique=False)
    op.create_index(op.f("ix_assets_plant_id"), "assets", ["plant_id"], unique=False)
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_sessions_expires_at"), "refresh_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_sessions_token_hash"), "refresh_sessions", ["token_hash"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id"), "refresh_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("reported_by", sa.Uuid(), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="incident_priority",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "ASSIGNED",
                "IN_PROGRESS",
                "WAITING",
                "RESOLVED",
                "CLOSED",
                name="incident_status",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "reported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("downtime_minutes", sa.Integer(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reported_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidents_asset_id"), "incidents", ["asset_id"], unique=False)
    op.create_index(op.f("ix_incidents_assigned_to"), "incidents", ["assigned_to"], unique=False)
    op.create_index(op.f("ix_incidents_company_id"), "incidents", ["company_id"], unique=False)
    op.create_index(
        "ix_incidents_company_priority", "incidents", ["company_id", "priority"], unique=False
    )
    op.create_index(
        "ix_incidents_company_reported", "incidents", ["company_id", "reported_at"], unique=False
    )
    op.create_index(
        "ix_incidents_company_status", "incidents", ["company_id", "status"], unique=False
    )
    op.create_index(op.f("ix_incidents_plant_id"), "incidents", ["plant_id"], unique=False)
    op.create_index(op.f("ix_incidents_reported_by"), "incidents", ["reported_by"], unique=False)
    op.create_table(
        "work_orders",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CORRECTIVE",
                "PREVENTIVE",
                "INSPECTION",
                "IMPROVEMENT",
                name="work_order_type",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="work_order_priority",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "ASSIGNED",
                "IN_PROGRESS",
                "WAITING",
                "COMPLETED",
                "CANCELLED",
                name="work_order_status",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_duration", sa.Integer(), nullable=True),
        sa.Column("real_duration", sa.Integer(), nullable=True),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "number", name="uq_work_orders_company_number"),
    )
    op.create_index(op.f("ix_work_orders_asset_id"), "work_orders", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_work_orders_assigned_to"), "work_orders", ["assigned_to"], unique=False
    )
    op.create_index(op.f("ix_work_orders_company_id"), "work_orders", ["company_id"], unique=False)
    op.create_index(
        "ix_work_orders_company_scheduled",
        "work_orders",
        ["company_id", "scheduled_date"],
        unique=False,
    )
    op.create_index(
        "ix_work_orders_company_status", "work_orders", ["company_id", "status"], unique=False
    )
    op.create_index(op.f("ix_work_orders_created_by"), "work_orders", ["created_by"], unique=False)
    op.create_index(
        op.f("ix_work_orders_incident_id"), "work_orders", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_work_orders_number"), "work_orders", ["number"], unique=False)
    op.create_index(op.f("ix_work_orders_plant_id"), "work_orders", ["plant_id"], unique=False)
    op.create_index(
        op.f("ix_work_orders_scheduled_date"), "work_orders", ["scheduled_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_orders_scheduled_date"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_plant_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_number"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_incident_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_created_by"), table_name="work_orders")
    op.drop_index("ix_work_orders_company_status", table_name="work_orders")
    op.drop_index("ix_work_orders_company_scheduled", table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_company_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_assigned_to"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_asset_id"), table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index(op.f("ix_incidents_reported_by"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_plant_id"), table_name="incidents")
    op.drop_index("ix_incidents_company_status", table_name="incidents")
    op.drop_index("ix_incidents_company_reported", table_name="incidents")
    op.drop_index("ix_incidents_company_priority", table_name="incidents")
    op.drop_index(op.f("ix_incidents_company_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_assigned_to"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_asset_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions")
    op.drop_index(op.f("ix_refresh_sessions_token_hash"), table_name="refresh_sessions")
    op.drop_index(op.f("ix_refresh_sessions_expires_at"), table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index(op.f("ix_assets_plant_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_name"), table_name="assets")
    op.drop_index("ix_assets_company_status", table_name="assets")
    op.drop_index(op.f("ix_assets_company_id"), table_name="assets")
    op.drop_index("ix_assets_company_criticality", table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_company_id"), table_name="users")
    op.drop_index(op.f("ix_users_active"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_plants_company_id"), table_name="plants")
    op.drop_index(op.f("ix_plants_active"), table_name="plants")
    op.drop_table("plants")
    op.drop_index(op.f("ix_companies_tax_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_active"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
