"""add v0.2 operations modules

Revision ID: 62266bc51e54
Revises: 55a60c1e5af7
Create Date: 2026-08-12 16:04:21.887848
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "62266bc51e54"
down_revision: str | None = "55a60c1e5af7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_items",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("stock", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("minimum_stock", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=24), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "code", name="uq_inventory_company_code"),
    )
    op.create_index(
        "ix_inventory_company_active", "inventory_items", ["company_id", "active"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_items_company_id"), "inventory_items", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_inventory_items_name"), "inventory_items", ["name"], unique=False)
    op.create_table(
        "inventory_movements",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "RECEIPT",
                "CONSUMPTION",
                "ADJUSTMENT",
                name="inventory_movement_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("resulting_stock", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_movements_company_created",
        "inventory_movements",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_company_id"),
        "inventory_movements",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_item_id"), "inventory_movements", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_movements_user_id"), "inventory_movements", ["user_id"], unique=False
    )
    op.create_table(
        "preventive_plans",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "frequency_type",
            sa.Enum(
                "DAYS",
                "WEEKS",
                "MONTHS",
                "YEARS",
                name="frequency_type",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("frequency_value", sa.Integer(), nullable=False),
        sa.Column("next_execution", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estimated_duration", sa.Integer(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="preventive_priority",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "asset_id", "name", name="uq_preventive_company_asset_name"
        ),
    )
    op.create_index(
        "ix_preventive_company_active", "preventive_plans", ["company_id", "active"], unique=False
    )
    op.create_index(
        "ix_preventive_company_next",
        "preventive_plans",
        ["company_id", "next_execution"],
        unique=False,
    )
    op.create_index(
        op.f("ix_preventive_plans_asset_id"), "preventive_plans", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_preventive_plans_assigned_to"), "preventive_plans", ["assigned_to"], unique=False
    )
    op.create_index(
        op.f("ix_preventive_plans_company_id"), "preventive_plans", ["company_id"], unique=False
    )
    op.create_table(
        "technical_documents",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "MANUAL",
                "ELECTRICAL_SCHEMATIC",
                "PROCEDURE",
                "SAFETY",
                "OTHER",
                name="document_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        "ix_documents_company_uploaded",
        "technical_documents",
        ["company_id", "uploaded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_documents_asset_id"), "technical_documents", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_technical_documents_company_id"),
        "technical_documents",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_documents_uploaded_by"),
        "technical_documents",
        ["uploaded_by"],
        unique=False,
    )
    op.add_column("work_orders", sa.Column("preventive_plan_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_work_orders_preventive_plan_id"),
        "work_orders",
        ["preventive_plan_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_work_orders_preventive_plan_id",
        "work_orders",
        "preventive_plans",
        ["preventive_plan_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_work_orders_preventive_plan_id", "work_orders", type_="foreignkey")
    op.drop_index(op.f("ix_work_orders_preventive_plan_id"), table_name="work_orders")
    op.drop_column("work_orders", "preventive_plan_id")
    op.drop_index(op.f("ix_technical_documents_uploaded_by"), table_name="technical_documents")
    op.drop_index(op.f("ix_technical_documents_company_id"), table_name="technical_documents")
    op.drop_index(op.f("ix_technical_documents_asset_id"), table_name="technical_documents")
    op.drop_index("ix_documents_company_uploaded", table_name="technical_documents")
    op.drop_table("technical_documents")
    op.drop_index(op.f("ix_preventive_plans_company_id"), table_name="preventive_plans")
    op.drop_index(op.f("ix_preventive_plans_assigned_to"), table_name="preventive_plans")
    op.drop_index(op.f("ix_preventive_plans_asset_id"), table_name="preventive_plans")
    op.drop_index("ix_preventive_company_next", table_name="preventive_plans")
    op.drop_index("ix_preventive_company_active", table_name="preventive_plans")
    op.drop_table("preventive_plans")
    op.drop_index(op.f("ix_inventory_movements_user_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_item_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_company_id"), table_name="inventory_movements")
    op.drop_index("ix_inventory_movements_company_created", table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index(op.f("ix_inventory_items_name"), table_name="inventory_items")
    op.drop_index(op.f("ix_inventory_items_company_id"), table_name="inventory_items")
    op.drop_index("ix_inventory_company_active", table_name="inventory_items")
    op.drop_table("inventory_items")
    # ### end Alembic commands ###
