"""add v0.3 document intelligence

Revision ID: c098bdf2b89f
Revises: 62266bc51e54
Create Date: 2026-08-12 16:24:37.446678
"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

revision: str = "c098bdf2b89f"
down_revision: str | None = "62266bc51e54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_query_logs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_queries_company_created", "ai_query_logs", ["company_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_ai_query_logs_asset_id"), "ai_query_logs", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_ai_query_logs_company_id"), "ai_query_logs", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_ai_query_logs_user_id"), "ai_query_logs", ["user_id"], unique=False)
    op.create_table(
        "knowledge_chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["technical_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunks_document_index"),
    )
    op.create_index(
        "ix_chunks_company_asset", "knowledge_chunks", ["company_id", "asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_asset_id"), "knowledge_chunks", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_company_id"), "knowledge_chunks", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_document_id"), "knowledge_chunks", ["document_id"], unique=False
    )
    op.create_index(
        "ix_chunks_embedding_hnsw",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.add_column(
        "technical_documents",
        sa.Column(
            "index_status",
            sa.Enum(
                "PENDING",
                "INDEXING",
                "READY",
                "FAILED",
                "UNSUPPORTED",
                name="document_index_status",
                native_enum=False,
                length=24,
            ),
            server_default="PENDING",
            nullable=False,
        ),
    )
    op.add_column(
        "technical_documents", sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "technical_documents", sa.Column("index_error", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "technical_documents", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "technical_documents",
        sa.Column("chunk_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "technical_documents",
        sa.Column("embedded_chunk_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "technical_documents", sa.Column("embedding_model", sa.String(length=80), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("technical_documents", "embedding_model")
    op.drop_column("technical_documents", "embedded_chunk_count")
    op.drop_column("technical_documents", "chunk_count")
    op.drop_column("technical_documents", "content_hash")
    op.drop_column("technical_documents", "index_error")
    op.drop_column("technical_documents", "indexed_at")
    op.drop_column("technical_documents", "index_status")
    op.drop_index(
        "ix_chunks_embedding_hnsw", table_name="knowledge_chunks", postgresql_using="hnsw"
    )
    op.drop_index(op.f("ix_knowledge_chunks_document_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_company_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_asset_id"), table_name="knowledge_chunks")
    op.drop_index("ix_chunks_company_asset", table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_ai_query_logs_user_id"), table_name="ai_query_logs")
    op.drop_index(op.f("ix_ai_query_logs_company_id"), table_name="ai_query_logs")
    op.drop_index(op.f("ix_ai_query_logs_asset_id"), table_name="ai_query_logs")
    op.drop_index("ix_ai_queries_company_created", table_name="ai_query_logs")
    op.drop_table("ai_query_logs")
    # ### end Alembic commands ###
