[build]
builder = "DOCKERFILE"
dockerfilePath = "/Dockerfile"
watchPatterns = ["/frontend/**"]

[deploy]
healthcheckPath = "/login"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
overlapSeconds = 20
drainingSeconds = 30
