const labels: Record<string, string> = {
  ACTIVE: "Activo",
  STOPPED: "Parado",
  MAINTENANCE: "En mantenimiento",
  OUT_OF_SERVICE: "Fuera de servicio",
  LOW: "Baja",
  MEDIUM: "Media",
  HIGH: "Alta",
  CRITICAL: "Critica",
  OPEN: "Abierta",
  ASSIGNED: "Asignada",
  IN_PROGRESS: "En curso",
  WAITING: "En espera",
  PENDING_VALIDATION: "Pendiente de validacion",
  RESOLVED: "Resuelta",
  CLOSED: "Cerrada",
  COMPLETED: "Completada",
  CANCELLED: "Cancelada",
  LEAD: "Tecnico principal",
  SUPPORT: "Apoyo",
  COMMENT: "Comentario",
  MEASUREMENT: "Medicion",
  WORK_LOG: "Trabajo realizado",
  CAUSE: "Causa",
  SOLUTION: "Solucion",
  CREATED: "Creada",
  UPDATED: "Actualizada",
  PARTICIPANT_ADDED: "Tecnico incorporado",
  PARTICIPANT_REMOVED: "Tecnico retirado",
  STARTED: "Intervencion iniciada",
  PAUSED: "Intervencion pausada",
  RESUMED: "Intervencion reanudada",
  NOTE_ADDED: "Nota anadida",
  CHECKLIST_UPDATED: "Checklist actualizado",
  MATERIAL_CONSUMED: "Material consumido",
  MATERIAL_RETURNED: "Material devuelto",
  STATUS_CHANGED: "Estado actualizado",
  VALIDATED: "Trabajo validado",
  REOPENED: "Orden reabierta",
  REMOVED: "Retirado",
  CORRECTIVE: "Correctivo",
  PREVENTIVE: "Preventivo",
  INSPECTION: "Inspeccion",
  IMPROVEMENT: "Mejora",
  SUPER_ADMIN: "Superadministrador",
  ADMIN: "Administrador",
  MAINTENANCE_MANAGER: "Responsable de mantenimiento",
  TECHNICIAN: "Tecnico",
  VIEWER: "Consulta",
  DAYS: "Dias",
  WEEKS: "Semanas",
  MONTHS: "Meses",
  YEARS: "Anos",
  RECEIPT: "Entrada",
  CONSUMPTION: "Consumo",
  ADJUSTMENT: "Ajuste",
  RETURN: "Devolucion",
  MANUAL: "Manual",
  ELECTRICAL_SCHEMATIC: "Esquema electrico",
  PROCEDURE: "Procedimiento",
  SAFETY: "Seguridad",
  OTHER: "Otro",
  PENDING: "Pendiente",
  SYNCING: "Sincronizando",
  CONFLICT: "Conflicto",
  INDEXING: "Indexando",
  READY: "Disponible",
  FAILED: "Error",
  UNSUPPORTED: "No compatible",
  TRIAL: "Prueba",
  SUSPENDED: "Suspendida",
  EXPIRED: "Caducada",
  DEMO: "Demo",
  PROFESSIONAL: "Profesional",
  STARTER: "Starter",
  PRO: "Pro",
  INDUSTRIAL: "Industrial",
  ENTERPRISE: "Enterprise",
  INACTIVE: "Inactiva",
  ACCEPTED: "Aceptada",
  REVOKED: "Revocada",
  WORK_ORDER_ASSIGNED: "Trabajo asignado",
  CRITICAL_INCIDENT: "Incidencia critica",
  PREVENTIVE_DUE: "Preventivo proximo",
  PREVENTIVE_OVERDUE: "Preventivo vencido",
  LOW_STOCK: "Stock bajo",
  TRIAL_EXPIRING: "Prueba proxima a caducar",
};

export function labelFor(value: string): string {
  return labels[value] ?? value;
}

export function formatDate(value: string | null, includeTime = false): string {
  if (!value) return "Sin fecha";
  return new Intl.DateTimeFormat("es-ES", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    ...(includeTime ? { hour: "2-digit", minute: "2-digit" } : {}),
  }).format(new Date(value));
}

export function initials(name: string): string {
  return name
    .split(" ")
    .slice(0, 2)
    .map((part) => part[0])
    .join("")
    .toUpperCase();
}
