from enum import StrEnum


class UserRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    MAINTENANCE_MANAGER = "MAINTENANCE_MANAGER"
    TECHNICIAN = "TECHNICIAN"
    VIEWER = "VIEWER"


class CompanyPlan(StrEnum):
    DEMO = "DEMO"
    TRIAL = "TRIAL"
    STARTER = "STARTER"
    PRO = "PRO"
    INDUSTRIAL = "INDUSTRIAL"
    ENTERPRISE = "ENTERPRISE"
    PROFESSIONAL = "PROFESSIONAL"


class SubscriptionStatus(StrEnum):
    TRIAL = "TRIAL"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"


class CompanyModule(StrEnum):
    PREVENTIVE = "PREVENTIVE"
    INVENTORY = "INVENTORY"
    DOCUMENTS = "DOCUMENTS"
    KNOWLEDGE = "KNOWLEDGE"


class AssetStatus(StrEnum):
    ACTIVE = "ACTIVE"
    STOPPED = "STOPPED"
    MAINTENANCE = "MAINTENANCE"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"


class Criticality(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Priority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(StrEnum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING = "WAITING"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class WorkOrderType(StrEnum):
    CORRECTIVE = "CORRECTIVE"
    PREVENTIVE = "PREVENTIVE"
    INSPECTION = "INSPECTION"
    IMPROVEMENT = "IMPROVEMENT"


class WorkOrderStatus(StrEnum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING = "WAITING"
    PENDING_VALIDATION = "PENDING_VALIDATION"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class WorkOrderParticipantRole(StrEnum):
    LEAD = "LEAD"
    TECHNICIAN = "TECHNICIAN"
    SUPPORT = "SUPPORT"


class WorkSessionEndReason(StrEnum):
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REMOVED = "REMOVED"


class WorkOrderNoteType(StrEnum):
    COMMENT = "COMMENT"
    MEASUREMENT = "MEASUREMENT"
    WORK_LOG = "WORK_LOG"
    CAUSE = "CAUSE"
    SOLUTION = "SOLUTION"


class WorkOrderEventType(StrEnum):
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    ASSIGNED = "ASSIGNED"
    PARTICIPANT_ADDED = "PARTICIPANT_ADDED"
    PARTICIPANT_REMOVED = "PARTICIPANT_REMOVED"
    STARTED = "STARTED"
    PAUSED = "PAUSED"
    RESUMED = "RESUMED"
    NOTE_ADDED = "NOTE_ADDED"
    STATUS_CHANGED = "STATUS_CHANGED"
    COMPLETED = "COMPLETED"
    VALIDATED = "VALIDATED"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"


class FrequencyType(StrEnum):
    DAYS = "DAYS"
    WEEKS = "WEEKS"
    MONTHS = "MONTHS"
    YEARS = "YEARS"


class InventoryMovementType(StrEnum):
    RECEIPT = "RECEIPT"
    CONSUMPTION = "CONSUMPTION"
    ADJUSTMENT = "ADJUSTMENT"


class DocumentType(StrEnum):
    MANUAL = "MANUAL"
    ELECTRICAL_SCHEMATIC = "ELECTRICAL_SCHEMATIC"
    PROCEDURE = "PROCEDURE"
    SAFETY = "SAFETY"
    OTHER = "OTHER"


class DocumentIndexStatus(StrEnum):
    PENDING = "PENDING"
    INDEXING = "INDEXING"
    READY = "READY"
    FAILED = "FAILED"
    UNSUPPORTED = "UNSUPPORTED"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class NotificationType(StrEnum):
    WORK_ORDER_ASSIGNED = "WORK_ORDER_ASSIGNED"
    CRITICAL_INCIDENT = "CRITICAL_INCIDENT"
    PREVENTIVE_DUE = "PREVENTIVE_DUE"
    PREVENTIVE_OVERDUE = "PREVENTIVE_OVERDUE"
    LOW_STOCK = "LOW_STOCK"
    TRIAL_EXPIRING = "TRIAL_EXPIRING"
